language: python

python:

  - "2.7"

install:
  - pip install codecov
  - pip install coverage


script: 
  - python helloworld.py
  - coverage run helloworld.py

after_success:
  - codecov --token=fede63c3-2737-437f-b30e-48d08381ab70